"""
Django settings for amango project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.contrib.messages import constants as message_constants

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Environment-driven settings
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
#
# Locally (nothing set): behaves exactly like before — DEBUG on, insecure
# dev key, any host allowed. In production, set DJANGO_DEBUG=False,
# DJANGO_SECRET_KEY=<a real secret>, and DJANGO_ALLOWED_HOSTS to switch modes.

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

_DEV_SECRET_KEY = 'django-insecure-6w=q2=1tk2yxa(11t6fnz2=&8%2sh2h54%l3+n*ne--w7!uo-7'
# `or`, not .get()'s default arg — an env var can be *present but empty*
# (e.g. a blank line in .env), which .get()'s default wouldn't catch.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or _DEV_SECRET_KEY

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

if not DEBUG:
    # Fail loudly at startup rather than silently deploying with dev
    # settings — a wrong/missing secret key or host list in production is
    # a security bug, not something that should just quietly "still work".
    if SECRET_KEY == _DEV_SECRET_KEY:
        raise RuntimeError(
            'DJANGO_DEBUG=False but DJANGO_SECRET_KEY was not set. '
            'Refusing to run in production with the insecure dev key.'
        )
    if not ALLOWED_HOSTS:
        raise RuntimeError(
            'DJANGO_DEBUG=False but DJANGO_ALLOWED_HOSTS was not set. '
            'Refusing to run in production with no allowed hosts.'
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mango',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'amango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'amango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

_DB_ENGINE = os.environ.get('AMANGO_DB_ENGINE', 'postgresql')

if _DB_ENGINE == 'mysql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('AMANGO_DB_NAME', 'amangodevdb'),
            'USER': os.environ.get('AMANGO_DB_USER', 'root'),
            'PASSWORD': os.environ.get('AMANGO_DB_PASSWORD', 'ACW1#6030@smalmg'),
            'HOST': os.environ.get('AMANGO_DB_HOST', 'localhost'),
            'PORT': os.environ.get('AMANGO_DB_PORT', '3306'),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }
elif _DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('AMANGO_DB_NAME', 'AMANGODB'),
            'USER': os.environ.get('AMANGO_DB_USER', 'postgres'),
            'PASSWORD': os.environ.get('AMANGO_DB_PASSWORD', 'ACW1#6030@smalmg'),
            'HOST': os.environ.get('AMANGO_DB_HOST', 'localhost'),
            'PORT': os.environ.get('AMANGO_DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/6.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# django.contrib.messages tags mapped to Bootstrap 5 alert classes

MESSAGE_TAGS = {
    message_constants.DEBUG: 'secondary',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
