services:
  amango:
    build: .
    image: amango-app:v1
    container_name: amango-container
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${AMANGO_DB_NAME}
      POSTGRES_USER: ${AMANGO_DB_USER}
      POSTGRES_PASSWORD: ${AMANGO_DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${AMANGO_DB_USER} -d ${AMANGO_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
