# Generated by Django 6.1 on 2026-08-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangousersmodel',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
